source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~>1.6.0'
gem 'json', '~>2.0'
gem 'sqlite3'
gem 'sequel'
gem 'sinatra'
