source 'https://rubygems.org'

group :development, :test do
  gem 'minitest'
  gem 'pact-consumer-minitest', path: '../../'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~>1.5.2'
gem 'json', '~>1.8.0'
gem 'httparty'
