source 'https://rubygems.org'

group :development, :test do
  gem 'minitest'
  gem 'pact-consumer-minitest', path: '../../'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~>2.2.14'
gem 'json', '~>2.12.0'
gem 'httparty'
